### ISSUE TITLE
GenerateSplashAssets Fails 

### ISSUE THREAD

**Issue by dansiegel** [unoplatform/uno.resizetizer#178]
## Current behavior

The Build fails with the following errors

**Windows**
```
Error	MSB4018	The "GenerateSplashAssets_8fdbe6f9ea0dffe54098cbb6a8c2002d965d1a7a" task failed unexpectedly.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Uno.Resizetizer.GenerateSplashAssets_8fdbe6f9ea0dffe54098cbb6a8c2002d965d1a7a.Execute() in D:\a\uno.resizetizer\uno.resizetizer\src\Resizetizer\src\GenerateSplashAssets.cs:line 24
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	HelloWorld.Windows	C:\Users\dsieg\.nuget\packages\uno.resizetizer\1.2.0-dev.68\build\Uno.Resizetizer.windows.skia.targets
```

**Apple**
```
Error	MSB4018	The "GenerateSplashStoryboard_8fdbe6f9ea0dffe54098cbb6a8c2002d965d1a7a" task failed unexpectedly.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Uno.Resizetizer.GenerateSplashStoryboard_8fdbe6f9ea0dffe54098cbb6a8c2002d965d1a7a.Execute() in D:\a\uno.resizetizer\uno.resizetizer\src\Resizetizer\src\GenerateSplashStoryboard.cs:line 25
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	HelloWorld.Mobile	C:\Users\dsieg\.nuget\packages\uno.resizetizer\1.2.0-dev.68\build\Uno.Resizetizer.apple.targets
```

**Android**
```
Error	MSB4018	The "GenerateSplashAndroidResources_8fdbe6f9ea0dffe54098cbb6a8c2002d965d1a7a" task failed unexpectedly.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Uno.Resizetizer.GenerateSplashAndroidResources_8fdbe6f9ea0dffe54098cbb6a8c2002d965d1a7a.Execute() in D:\a\uno.resizetizer\uno.resizetizer\src\Resizetizer\src\GenerateSplashAndroidResources.cs:line 26
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	HelloWorld.Mobile	C:\Users\dsieg\.nuget\packages\uno.resizetizer\1.2.0-dev.68\build\Uno.Resizetizer.android.targets
```

## Expected behavior

The build should succeed or at least fail with a more useful error.

## How to reproduce it (as minimally and precisely as possible)

Run the e2e app on for Prism on the `dev/ds/uno-updates` branch.

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [x] Build tasks

**Comment by pictos** [comment]
@dansiegel can you provide the link to the repo?

**Comment by dansiegel** [comment]
https://github.com/PrismLibrary/Prism/tree/dev/ds/uno-updates
