### ISSUE TITLE
"WinAppSdkGenerateAppxManifest" task failed unexpectedly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.resizetizer#296]
Templates version:- 5.3.2 
The app was created using the above cli. 

But when trying to run windows packaged then i was getting this error. 
```
\MauiEmbeddingApp.MauiControls.dll
1>MauiEmbeddingApp.MauiControls -> F:\source\1916\MauiEmbeddingApp\MauiEmbeddingApp.MauiControls\bin\Debug\net8.0-android\MauiEmbeddingApp.MauiControls.dll
2>------ Build started: Project: MauiEmbeddingApp, Configuration: Debug Any CPU ------
2>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
2>MauiEmbeddingApp -> F:\source\1916\MauiEmbeddingApp\MauiEmbeddingApp\bin\Debug\net8.0-windows10.0.19041\MauiEmbeddingApp.dll
2>C:\Users\DarshPatel\.nuget\packages\microsoft.windowsappsdk\1.5.240607001\buildTransitive\Microsoft.Build.Msix.Packaging.targets(921,5): error APPX0002: Task 'WinAppSdkGenerateAppxManifest' failed. Object reference not set to an instance of an object.
2>C:\Users\DarshPatel\.nuget\packages\microsoft.windowsappsdk\1.5.240607001\buildTransitive\Microsoft.Build.Msix.Packaging.targets(921,5): error APPX0002:
2>C:\Users\DarshPatel\.nuget\packages\microsoft.windowsappsdk\1.5.240607001\buildTransitive\Microsoft.Build.Msix.Packaging.targets(921,5): error MSB4018: The "WinAppSdkGenerateAppxManifest" task failed unexpectedly.
2>C:\Users\DarshPatel\.nuget\packages\microsoft.windowsappsdk\1.5.240607001\buildTransitive\Microsoft.Build.Msix.Packaging.targets(921,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
2>C:\Users\DarshPatel\.nuget\packages\microsoft.windowsappsdk\1.5.240607001\buildTransitive\Microsoft.Build.Msix.Packaging.targets(921,5): error MSB4018:    at Microsoft.Build.Msix.AppxManifest.WinAppSdkGenerateAppxManifest.ProcessDocument()
2>C:\Users\DarshPatel\.nuget\packages\microsoft.windowsappsdk\1.5.240607001\buildTransitive\Microsoft.Build.Msix.Packaging.targets(921,5): error MSB4018:    at Microsoft.Build.Msix.AppxManifest.WinAppSdkGenerateAppxManifest.ExecuteImplementation()
2>C:\Users\DarshPatel\.nuget\packages\microsoft.windowsappsdk\1.5.240607001\buildTransitive\Microsoft.Build.Msix.Packaging.targets(921,5): error MSB4018:    at Microsoft.Build.Msix.AppxPackagingTaskHelper.Execute(String file)
2>C:\Users\DarshPatel\.nuget\packages\microsoft.windowsappsdk\1.5.240607001\buildTransitive\Microsoft.Build.Msix.Packaging.targets(921,5): error MSB4018:    at Microsoft.Build.Msix.AppxManifest.WinAppSdkGenerateAppxManifest.Execute()
2>C:\Users\DarshPatel\.nuget\packages\microsoft.windowsappsdk\1.5.240607001\buildTransitive\Microsoft.Build.Msix.Packaging.targets(921,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>C:\Users\DarshPatel\.nuget\packages\microsoft.windowsappsdk\1.5.240607001\buildTransitive\Microsoft.Build.Msix.Packaging.targets(921,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
2>Done building project "MauiEmbeddingApp.csproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 6:15 PM and took 15.728 seconds ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
========== Deploy completed at 6:15 PM and took 15.728 seconds ==========

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

_Originally posted by @Darsh0307 in https://github.com/unoplatform/uno.extensions/issues/2244#issuecomment-2168834192_

**Comment by jeromelaban** [comment]
May be fixed by resizetizer 1.5.0 (latest 5.3 sdk/template stable)

**Comment by jeromelaban** [comment]
I cannot reproduce with the 5.3.5 template.

**Comment by Darsh0307** [comment]
Closed , Working fine for uno.templates:- 5.3.5
