### ISSUE TITLE
`TypeInitializationException` on Resizetizer

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.resizetizer#315]
## Current behavior

After creating a blank Uno app from wizard, I'm getting the following error when trying to launch the WinAppSDK target:

```
The "GenerateSplashAssets_fe37862be6f8fb908991583ae0de30f0a4023685" task failed unexpectedly.
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at Svg.Skia.SKSvgSettings..ctor() in /_/src/Svg.Skia/SKSvgSettings.cs:line 22
   at Svg.Skia.SKSvg..ctor() in /_/src/Svg.Skia/SKSvg.Model.cs:line 55
   at Uno.Resizetizer.SkiaSharpSvgTools..ctor(String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger)
   at Uno.Resizetizer.SkiaSharpTools.Create(Boolean isVector, String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger)
   at Uno.Resizetizer.SkiaSharpAppIconTools..ctor(ResizeImageInfo info, ILogger logger)
   at Uno.Resizetizer.GenerateSplashAssets_fe37862be6f8fb908991583ae0de30f0a4023685.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

## Expected behavior

No error.

## How to reproduce it (as minimally and precisely as possible)

[UnoApp13.zip](https://github.com/user-attachments/files/16991927/UnoApp13.zip)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by morning4coffe-dev** [comment]
@MartinZikmund This error only appears with Uno.Sdk [5.5.0-dev.13](https://www.nuget.org/packages/Uno.Sdk/5.5.0-dev.13) - resizetizer 1.6.0-dev.26
